conversionRhapsody <- structure(list(COHORT_OPAL = c("andis", "desir", "andis", "andis",
"dcs", "desir", "mdc", "desir", "desir", "dcs", "andis", "godarts",
"desir", "botnia", "mdc", "abos", "colaus", "andis", "godarts",
"desir", "botnia", "mdc", "abos", "colaus", "botnia", "desir",
"desir", "andis", "dcs", "godarts", "desir", "botnia", "mdc",
"abos", "desir", "andis", "desir", "andis", "desir", "desir",
"desir", "desir", "andis", "desir", "desir", "desir", "desir",
"desir", "desir", "dcs", "desir", "andis", "desir", "desir",
"desir", "desir", "mdc", "abos", "abos", "ludc-gb", "ludc-gb",
"ludc-gb", "ludc-gb", "ludc-gb", "addition-pro", "addition-dk","i1v-mc-eian"
), TESTCD_IN_DB = c("CHOL", "CHOL", "CPEPTIDE", "CREAT", "CREAT",
"CREAT", "CREAT", "CRP", "CYSTATC", "DIABP", "DIABP", "DIABP",
"DIABP", "DIABP", "DIABP", "DIABP", "DIABP", "SYSBP", "SYSBP",
"SYSBP", "SYSBP", "SYSBP", "SYSBP", "SYSBP", "FATACFR", "FERRITIN",
"FIBRINO", "GAD", "GAD", "GAD1", "GAD", "GAD", "GAD", "GAD",
"GGT", "GLU", "GLUC", "HDL", "HDL", "HGB", "INSULIN", "K", "LDL",
"LDL", "LPA", "PLAT", "RBC", "SODIUM", "SOMATRO", "SYSBP", "TFERRIN",
"TRIG", "TRIG", "URATE", "WBC", "HBA1C", "HBA1C", "HBA1C", "CPEPTIDE",
"GHRELIN", "GIP", "GLP1", "HEIGHT", "INSULIN", "HBA1C", "HBA1C","HBA1C"
), TARGET_TESTCD = c("CHOL", "CHOL", "CPEPTIDE", "CREAT", "CREAT",
"CREAT", "CREAT", "CRP", "CYSTATC", "DIABP", "DIABP", "DIABP",
"DIABP", "DIABP", "DIABP", "DIABP", "DIABP", "SYSBP", "SYSBP",
"SYSBP", "SYSBP", "SYSBP", "SYSBP", "SYSBP", "FATACFR", "FERRITIN",
"FIBRINO", "GADAB", "GADAB", "GADAB", "GADAB", "GADAB", "GADAB",
"GADAB", "GGT", "GLUC", "GLUC", "HDL", "HDL", "HGB", "INSULIN",
"K", "LDL", "LDL", "LPA", "PLAT", "RBC", "SODIUM", "SOMATRO",
"SYSBP", "TFERRIN", "TRIG", "TRIG", "URATE", "WBC", "HBA1C",
"HBA1C", "HBA1C", "CPEPTIDE", "GHRELIN", "GIP", "GLP1", "HEIGHT",
"INSULIN", "HBA1C", "HBA1C","HBA1C"), UNIT_IN_DB = c("mmol/l", "g/L",
"mmol/l", "µmol/l", "Umol/L", "mg/L", "mmol/l", "mg/L", "%",
"mmHG", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg",
"mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "µmol/l",
"umol/L", "g/L", "U/ml", "U/mL", "IU/mL", "U/mL", "U/mL", "U/mL",
"U/mL", "IU/L", "mmol/l", "g/L", "mmol/l", "g/L", "%", "uU/mL",
"mEq/L", "mmol/l", "g/L", "g/L", "10.3/mm3", "10.4/mm3", "mEq/L",
"ng/mL", "mmHG", "g/L", "mmol/l", "g/L", "mg/L", "10.2/mm3",
"%", "%", "%", "ng/mL", "pg/mL", "pg/mL", "pM", "m", "mIU/L",
"%", "%","%"), SOURCE_UNIT = c("mmol/l", "g/L", "mmol/l", "μmol/l",
"Umol/L", "mg/L", "mmol/l", "mg/L", "%", "mmHG", "mmHg", "mmHg",
"mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg",
"mmHg", "mmHg", "mmHg", "mmHg", "μmol/L", "umol/L", "g/L", "U/ml",
"U/mL", "IU/mL", "U/mL", "U/mL", "U/mL", "U/mL", "IU/L", "mmol/l",
"g/L", "mmol/l", "g/L", "%", "uU/mL", "mEq/L", "mmol/l", "g/L",
"g/L", "10.3/mm3", "10.4/mm3", "mEq/L", "ng/mL", "mmHG", "g/L",
"mmol/l", "g/L", "mg/L", "10.2/mm3", "%", "%", "%", "ng/mL",
"pg/mL", "pg/mL", "pM", "m", "mIU/L", "%", "%","%"), TARGET_CONVERSION_FACTOR = c("LBORRES * 1",
"LBORRES * 2.59", "LBORRES * 1", "LBORRES * 1", "LBORRES * 1",
"LBORRES * 8.84", "LBORRES * 1000", "LBORRES * 9.524", "LBORRES * 1",
"VSORRES * 1", "VSORRES * 1", "VSORRES * 1", "VSORRES * 1", "VSORRES * 1",
"VSORRES * 1", "VSORRES * 1", "VSORRES * 1", "VSORRES * 1", "VSORRES * 1",
"VSORRES * 1", "VSORRES * 1", "VSORRES * 1", "VSORRES * 1", "VSORRES * 1",
"LBORRES * 0.001", "LBORRES * 2.25", "LBORRES * 2.94", "LBORRES * 1",
"LBORRES * 1", "LBORRES * 1", "LBORRES * 1", "LBORRES * 1", "LBORRES * 1",
"LBORRES * 1", "LBORRES * 1", "LBORRES * 1", "LBORRES * 5.55",
"LBORRES * 1", "LBORRES * 2.59", "LBORRES * 10", "LBORRES * 1",
"LBORRES * 1", "LBORRES * 1", "LBORRES * 2.59", "LBORRES * 3.57",
"LBORRES * 1", "LBORRES * 0.01", "LBORRES * 1", "LBORRES * 1",
"VSORRES * 1", "LBORRES * 12.3", "LBORRES * 1", "LBORRES * 1.13",
"LBORRES * 5.95", "LBORRES * 0.1", "(LBORRES - 2.15)*10.929",
"(LBORRES*10.11 - 8.94) ", "(LBORRES - 2.15)*10.929", "LBORRES * 0.333",
"LBORRES * 3.371", "LBORRES * 0.2272", "LBORRES * 1", "LBORRES * 100",
"LBORRES * 1", "(LBORRES - 2.15)*10.929", "(LBORRES - 2.15)*10.929","(LBORRES - 2.15)*10.929"
), TARGET_UNIT = c("mmol/L", "mmol/L", "nmol/L", "umol/L", "umol/L",
"umol/L", "umol/L", "nmol/L", "mg/L", "mmHg", "mmHg", "mmHg",
"mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg", "mmHg",
"mmHg", "mmHg", "mmHg", "mmHg", "mmol/L", "pmol/L", "umol/L",
"kU/L", "kU/L", "kU/L", "kU/L", "kU/L", "kU/L", "kU/L", "IU/L",
"mmol/L", "mmol/L", "mmol/L", "mmol/L", "g/L", "uIU/mL", "mmol/L",
"mmol/L", "mmol/L", "umol/L", "10*9/L", "10*12/L", "mmol/L",
"ug/L", "mmHg", "umol/L", "mmol/L", "mmol/L", "umol/L", "10*9/L",
"mmol/mol", "mmol/mol", "mmol/mol", "nmol/L", "pmol/L", "pmol/L",
"pmol/L", "cm", "uIU/mL", "mmol/mol", "mmol/mol","mmol/mol"), SI_UNIT = c("mmol/L",
"mmol/L", "nmol/L", "umol/L", "umol/L", "umol/L", "umol/L", "nmol/L",
"mg/L", "kPa", "kPa", "kPa", "kPa", "kPa", "kPa", "kPa", "kPa",
"kPa", "kPa", "kPa", "kPa", "kPa", "kPa", "kPa", "mmol/L", "pmol/L",
"umol/L", "kU/L", "kU/L", "kU/L", "kU/L", "kU/L", "kU/L", "kU/L",
"ukat/L", "mmol/L", "mmol/L", "mmol/L", "mmol/L", "g/L", "pmol/L",
"mmol/L", "mmol/L", "mmol/L", "umol/L", "10*9/L", "10*12/L",
"mmol/L", "ug/L", "kPa", "umol/L", "mmol/L", "mmol/L", "umol/L",
"10*9/L", "mmol/mol", "mmol/mol", "mmol/mol", "nmol/L", "pmol/L",
"pmol/L", "pmol/L", "cm", "pmol/L", "mmol/mol", "mmol/mol","mmol/mol"),
    SI_CONVERSION_FACTOR = c("LBORRES * 1", "LBORRES * 2.59",
    "LBORRES * 1", "LBORRES * 1", "LBORRES * 1", "LBORRES * 8.84",
    "LBORRES * 1000", "LBORRES * 9.524", "LBORRES * 1", "VSORRES * 0.13",
    "VSORRES * 0.13", "VSORRES * 0.13", "VSORRES * 0.13", "VSORRES * 0.13",
    "VSORRES * 0.13", "VSORRES * 0.13", "VSORRES * 0.13", "VSORRES * 0.13",
    "VSORRES * 0.13", "VSORRES * 0.13", "VSORRES * 0.13", "VSORRES * 0.13",
    "VSORRES * 0.13", "VSORRES * 0.13", "LBORRES * 0.01", "LBORRES * 2.25",
    "LBORRES * 2.94", "LBORRES * 1", "LBORRES * 1", "LBORRES * 1",
    "LBORRES * 1", "LBORRES * 1", "LBORRES * 1", "LBORRES * 1",
    "LBORRES * 0,02", "LBORRES * 1", "LBORRES * 5.55", "LBORRES * 1",
    "LBORRES * 2.59", "LBORRES * 10", "LBORRES * 6.95", "LBORRES * 1",
    "LBORRES * 1", "LBORRES * 2.59", "LBORRES * 3.57", "LBORRES * 1",
    "LBORRES * 0.01", "LBORRES * 1", "LBORRES * 1", "VSORRES * 0.13",
    "LBORRES * 12.3", "LBORRES * 1", "LBORRES * 1.13", "LBORRES * 5.95",
    "LBORRES * 0.1", "(LBORRES - 2.15)*10.929", "(LBORRES*10.11 - 8.94)",
    "(LBORRES - 2.15)*10.929", "LBORRES * 0.333", "LBORRES * 3.371",
    "LBORRES * 0.2272", "LBORRES * 1", "LBORRES * 100", "LBORRES * 1",
    "(LBORRES - 2.15)*10.929", "(LBORRES - 2.15)*10.929", "(LBORRES - 2.15)*10.929")), .Names = c("COHORT_OPAL",
"TESTCD_IN_DB", "TARGET_TESTCD", "UNIT_IN_DB", "SOURCE_UNIT",
"TARGET_CONVERSION_FACTOR", "TARGET_UNIT", "SI_UNIT", "SI_CONVERSION_FACTOR"
), row.names = c(NA, -67L), class = "data.frame")
